import { IsNotEmpty, IsString } from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';

export class WalletVerificationDto {
    @ApiProperty({
        description: 'Stellar public key',
        example: 'G...',
    })
    @IsNotEmpty()
    @IsString()
    publicKey: string;

    @ApiProperty({
        description: 'Signature generated by signing the message with the private key',
        example: '...',
    })
    @IsNotEmpty()
    @IsString()
    signature: string;

    @ApiProperty({
        description: 'The raw data (message) that was signed',
        example: 'Signing in to SkillCert',
    })
    @IsNotEmpty()
    @IsString()
    data: string;
}
